<?php

query("CREATE TABLE IF NOT EXISTS `config` (`key` VARCHAR(32) NOT NULL PRIMARY KEY, `value` TEXT)");
query("CREATE TABLE IF NOT EXISTS `page` (`id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY, `page` TEXT)");
query("CREATE TABLE IF NOT EXISTS `content` (`id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY, `page` INT NOT NULL, `content` TEXT)");
query("CREATE TABLE IF NOT EXISTS `admin` (`id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY, `level` INT DEFAULT 0 NOT NULL, `name` VARCHAR(64) NOT NULL, `password` VARCHAR(64) NOT NULL, `email` VARCHAR(64) NOT NULL)");

?>
